### ISSUE TITLE
Connection to Slack fails

### ISSUE THREAD

**Issue by pirtil** [nullboundary/ArduinoSlack#3]
It seems SSL fingerprint has changed.
With this I was able to connect:

const char * slackSSLFingerprint = "AC 95 5A 58 B8 4E 0B CD B3 97 D2 88 68 F5 CA C1 0A 81 E3 6E"; //You can use https://www.grc.com/fingerprints.htm to get fingerprint for "slack.com"

**Comment by nullboundary** [comment]
Thanks for the heads up. I updated the repo with the new fingerprint.
